gen.o: gen.c ralloc.h ../common.h ../SDCCglobl.h ../SDCCset.h \
 ../../sdccconf.h ../SDCCerr.h ../SDCCmem.h ../../support/util/dbuf.h \
 ../SDCCast.h ../SDCCsymt.h ../SDCChasht.h ../SDCCval.h ../SDCCy.h \
 ../SDCCbitv.h ../SDCCicode.h ../SDCClabel.h ../SDCCBBlock.h \
 ../SDCCloop.h ../SDCCcse.h ../SDCCcflow.h ../SDCCdflow.h ../SDCClrange.h \
 ../SDCCptropt.h ../SDCCopt.h ../SDCCglue.h ../SDCCpeeph.h ../SDCCgen.h \
 ../SDCCicode.h ../SDCCdebug.h ../SDCCutil.h ../SDCCasm.h ../SDCCsystem.h \
 ../port.h ../SDCCargs.h ../../support/util/newalloc.h gen.h
main.o: main.c ../common.h ../SDCCglobl.h ../SDCCset.h ../../sdccconf.h \
 ../SDCCerr.h ../SDCCmem.h ../../support/util/dbuf.h ../SDCCast.h \
 ../SDCCsymt.h ../SDCChasht.h ../SDCCval.h ../SDCCy.h ../SDCCbitv.h \
 ../SDCCicode.h ../SDCClabel.h ../SDCCBBlock.h ../SDCCloop.h ../SDCCcse.h \
 ../SDCCcflow.h ../SDCCdflow.h ../SDCClrange.h ../SDCCptropt.h \
 ../SDCCopt.h ../SDCCglue.h ../SDCCpeeph.h ../SDCCgen.h ../SDCCicode.h \
 ../SDCCdebug.h ../SDCCutil.h ../SDCCasm.h ../SDCCsystem.h ../port.h \
 ../SDCCargs.h ../../support/util/newalloc.h \
 ../../support/util/dbuf_string.h ../../support/util/dbuf.h ralloc.h \
 peep.h peeph.rul
peep.o: peep.c ../common.h ../SDCCglobl.h ../SDCCset.h ../../sdccconf.h \
 ../SDCCerr.h ../SDCCmem.h ../../support/util/dbuf.h ../SDCCast.h \
 ../SDCCsymt.h ../SDCChasht.h ../SDCCval.h ../SDCCy.h ../SDCCbitv.h \
 ../SDCCicode.h ../SDCClabel.h ../SDCCBBlock.h ../SDCCloop.h ../SDCCcse.h \
 ../SDCCcflow.h ../SDCCdflow.h ../SDCClrange.h ../SDCCptropt.h \
 ../SDCCopt.h ../SDCCglue.h ../SDCCpeeph.h ../SDCCgen.h ../SDCCicode.h \
 ../SDCCdebug.h ../SDCCutil.h ../SDCCasm.h ../SDCCsystem.h ../port.h \
 ../SDCCargs.h ../../support/util/newalloc.h ../SDCCgen.h peep.h
ralloc.o: ralloc.c ralloc.h ../common.h ../SDCCglobl.h ../SDCCset.h \
 ../../sdccconf.h ../SDCCerr.h ../SDCCmem.h ../../support/util/dbuf.h \
 ../SDCCast.h ../SDCCsymt.h ../SDCChasht.h ../SDCCval.h ../SDCCy.h \
 ../SDCCbitv.h ../SDCCicode.h ../SDCClabel.h ../SDCCBBlock.h \
 ../SDCCloop.h ../SDCCcse.h ../SDCCcflow.h ../SDCCdflow.h ../SDCClrange.h \
 ../SDCCptropt.h ../SDCCopt.h ../SDCCglue.h ../SDCCpeeph.h ../SDCCgen.h \
 ../SDCCicode.h ../SDCCdebug.h ../SDCCutil.h ../SDCCasm.h ../SDCCsystem.h \
 ../port.h ../SDCCargs.h ../../support/util/newalloc.h gen.h \
 ../../support/util/dbuf_string.h ../../support/util/dbuf.h
ralloc2.o: ralloc2.cc ../SDCCralloc.hpp ../common.h ../SDCCglobl.h \
 ../SDCCset.h ../../sdccconf.h ../SDCCerr.h ../SDCCmem.h \
 ../../support/util/dbuf.h ../SDCCast.h ../SDCCsymt.h ../SDCChasht.h \
 ../SDCCval.h ../SDCCy.h ../SDCCbitv.h ../SDCCicode.h ../SDCClabel.h \
 ../SDCCBBlock.h ../SDCCloop.h ../SDCCcse.h ../SDCCcflow.h ../SDCCdflow.h \
 ../SDCClrange.h ../SDCCptropt.h ../SDCCopt.h ../SDCCglue.h \
 ../SDCCpeeph.h ../SDCCgen.h ../SDCCicode.h ../SDCCdebug.h ../SDCCutil.h \
 ../SDCCasm.h ../SDCCsystem.h ../port.h ../SDCCargs.h \
 ../../support/util/newalloc.h ../SDCCbtree.h ../SDCCtree_dec.hpp \
 ../SDCCsalloc.hpp ralloc.h ../common.h gen.h
