_atof.rel: _atof.c ../../device/include/ctype.h \
 ../../device/include/stdlib.h ../../device/include/stdbool.h
_schar2fs.rel: _schar2fs.c ../../device/include/float.h \
 ../../device/include/limits.h
_sint2fs.rel: _sint2fs.c ../../device/include/float.h \
 ../../device/include/limits.h
_slong2fs.rel: _slong2fs.c ../../device/include/float.h \
 ../../device/include/limits.h
_uchar2fs.rel: _uchar2fs.c ../../device/include/float.h \
 ../../device/include/limits.h
_uint2fs.rel: _uint2fs.c ../../device/include/float.h \
 ../../device/include/limits.h
_ulong2fs.rel: _ulong2fs.c ../../device/include/float.h \
 ../../device/include/limits.h
_fs2schar.rel: _fs2schar.c ../../device/include/float.h \
 ../../device/include/limits.h
_fs2sint.rel: _fs2sint.c ../../device/include/float.h \
 ../../device/include/limits.h
_fs2slong.rel: _fs2slong.c ../../device/include/float.h \
 ../../device/include/limits.h
_fs2uchar.rel: _fs2uchar.c ../../device/include/float.h \
 ../../device/include/limits.h
_fs2uint.rel: _fs2uint.c ../../device/include/float.h \
 ../../device/include/limits.h
_fs2ulong.rel: _fs2ulong.c ../../device/include/float.h \
 ../../device/include/limits.h
_fsadd.rel: _fsadd.c ../../device/include/float.h \
 ../../device/include/limits.h ../../device/include/stdbool.h \
 ../../device/include/sdcc-lib.h \
 ../../device/include/asm/default/features.h
_fsdiv.rel: _fsdiv.c ../../device/include/float.h \
 ../../device/include/limits.h
_fsmul.rel: _fsmul.c ../../device/include/float.h \
 ../../device/include/limits.h
_fssub.rel: _fssub.c ../../device/include/float.h \
 ../../device/include/limits.h
_fseq.rel: _fseq.c ../../device/include/float.h \
 ../../device/include/limits.h
_fslt.rel: _fslt.c ../../device/include/float.h \
 ../../device/include/limits.h
_fsneq.rel: _fsneq.c ../../device/include/float.h \
 ../../device/include/limits.h
fabsf.rel: fabsf.c ../../device/include/math.h \
 ../../device/include/errno.h
frexpf.rel: frexpf.c ../../device/include/math.h \
 ../../device/include/errno.h
ldexpf.rel: ldexpf.c ../../device/include/math.h \
 ../../device/include/errno.h
expf.rel: expf.c ../../device/include/math.h ../../device/include/errno.h \
 ../../device/include/stdbool.h
powf.rel: powf.c ../../device/include/math.h ../../device/include/errno.h
sincosf.rel: sincosf.c ../../device/include/math.h \
 ../../device/include/errno.h ../../device/include/stdbool.h
sinf.rel: sinf.c ../../device/include/math.h \
 ../../device/include/stdbool.h
cosf.rel: cosf.c ../../device/include/math.h \
 ../../device/include/stdbool.h
logf.rel: logf.c ../../device/include/math.h ../../device/include/errno.h
log10f.rel: log10f.c ../../device/include/math.h \
 ../../device/include/errno.h
sqrtf.rel: sqrtf.c ../../device/include/math.h \
 ../../device/include/errno.h
tancotf.rel: tancotf.c ../../device/include/math.h \
 ../../device/include/errno.h ../../device/include/stdbool.h
tanf.rel: tanf.c ../../device/include/math.h \
 ../../device/include/stdbool.h
cotf.rel: cotf.c ../../device/include/math.h ../../device/include/errno.h \
 ../../device/include/stdbool.h
asincosf.rel: asincosf.c ../../device/include/math.h \
 ../../device/include/errno.h ../../device/include/stdbool.h
asinf.rel: asinf.c ../../device/include/math.h \
 ../../device/include/stdbool.h
acosf.rel: acosf.c ../../device/include/math.h \
 ../../device/include/stdbool.h
atanf.rel: atanf.c ../../device/include/math.h \
 ../../device/include/errno.h
atan2f.rel: atan2f.c ../../device/include/math.h \
 ../../device/include/errno.h
sincoshf.rel: sincoshf.c ../../device/include/math.h \
 ../../device/include/errno.h ../../device/include/stdbool.h
sinhf.rel: sinhf.c ../../device/include/math.h \
 ../../device/include/stdbool.h
coshf.rel: coshf.c ../../device/include/math.h \
 ../../device/include/stdbool.h
tanhf.rel: tanhf.c ../../device/include/math.h \
 ../../device/include/errno.h
floorf.rel: floorf.c ../../device/include/math.h
ceilf.rel: ceilf.c ../../device/include/math.h
modff.rel: modff.c ../../device/include/math.h
errno.rel: errno.c
isinf.rel: isinf.c ../../device/include/float.h \
 ../../device/include/limits.h ../../device/include/math.h
isnan.rel: isnan.c ../../device/include/float.h \
 ../../device/include/limits.h ../../device/include/math.h
_fscmp.rel: _fscmp.c ../../device/include/float.h \
 ../../device/include/limits.h
_fsget1arg.rel: _fsget1arg.c ../../device/include/float.h \
 ../../device/include/limits.h
_fsget2args.rel: _fsget2args.c ../../device/include/float.h \
 ../../device/include/limits.h
_fsnormalize.rel: _fsnormalize.c ../../device/include/float.h \
 ../../device/include/limits.h
_fsreturnval.rel: _fsreturnval.c ../../device/include/float.h \
 ../../device/include/limits.h
_fsrshift.rel: _fsrshift.c ../../device/include/float.h \
 ../../device/include/limits.h
_fsswapargs.rel: _fsswapargs.c ../../device/include/float.h \
 ../../device/include/limits.h
_logexpf.rel: _logexpf.c ../../device/include/math.h
_divsint.rel: _divsint.c ../../device/include/sdcc-lib.h \
 ../../device/include/asm/default/features.h
_divuint.rel: _divuint.c ../../device/include/stdbool.h
_modsint.rel: _modsint.c ../../device/include/sdcc-lib.h \
 ../../device/include/asm/default/features.h
_moduint.rel: _moduint.c
_mulint.rel: _mulint.c
_divslong.rel: _divslong.c ../../device/include/sdcc-lib.h \
 ../../device/include/asm/default/features.h
_modslong.rel: _modslong.c ../../device/include/sdcc-lib.h \
 ../../device/include/asm/default/features.h
_modulong.rel: _modulong.c
_divulong.rel: _divulong.c ../../device/include/stdbool.h
_mullong.rel: _mullong.c
_rrulonglong.rel: _rrulonglong.c ../../device/include/stdint.h
_rrslonglong.rel: _rrslonglong.c ../../device/include/stdint.h
_rlulonglong.rel: _rlulonglong.c ../../device/include/stdint.h
_rlslonglong.rel: _rlslonglong.c ../../device/include/stdint.h
_mullonglong.rel: _mullonglong.c ../../device/include/stdint.h
_divslonglong.rel: _divslonglong.c ../../device/include/stdint.h \
 ../../device/include/stdbool.h
_divulonglong.rel: _divulonglong.c ../../device/include/stdint.h \
 ../../device/include/stdbool.h
_modslonglong.rel: _modslonglong.c ../../device/include/stdint.h \
 ../../device/include/stdbool.h
_modulonglong.rel: _modulonglong.c ../../device/include/stdint.h
isalnum.rel: isalnum.c ../../device/include/ctype.h
isalpha.rel: isalpha.c ../../device/include/ctype.h
isblank.rel: isblank.c ../../device/include/stdio.h \
 ../../device/include/stdarg.h ../../device/include/sdcc-lib.h \
 ../../device/include/asm/default/features.h ../../device/include/ctype.h
iscntrl.rel: iscntrl.c ../../device/include/ctype.h
isdigit.rel: isdigit.c ../../device/include/stdio.h \
 ../../device/include/stdarg.h ../../device/include/sdcc-lib.h \
 ../../device/include/asm/default/features.h ../../device/include/ctype.h
isgraph.rel: isgraph.c ../../device/include/ctype.h
islower.rel: islower.c ../../device/include/stdio.h \
 ../../device/include/stdarg.h ../../device/include/sdcc-lib.h \
 ../../device/include/asm/default/features.h ../../device/include/ctype.h
isprint.rel: isprint.c ../../device/include/ctype.h
ispunct.rel: ispunct.c ../../device/include/ctype.h
isspace.rel: isspace.c ../../device/include/ctype.h
isupper.rel: isupper.c ../../device/include/stdio.h \
 ../../device/include/stdarg.h ../../device/include/sdcc-lib.h \
 ../../device/include/asm/default/features.h ../../device/include/ctype.h
isxdigit.rel: isxdigit.c ../../device/include/ctype.h
tolower.rel: tolower.c ../../device/include/ctype.h
toupper.rel: toupper.c ../../device/include/ctype.h
atoi.rel: atoi.c ../../device/include/stdlib.h \
 ../../device/include/ctype.h ../../device/include/stdbool.h
atol.rel: atol.c ../../device/include/stdlib.h \
 ../../device/include/ctype.h ../../device/include/stdbool.h
atoll.rel: atoll.c ../../device/include/stdlib.h \
 ../../device/include/ctype.h ../../device/include/stdbool.h
strtol.rel: strtol.c ../../device/include/stdlib.h \
 ../../device/include/stdbool.h ../../device/include/ctype.h \
 ../../device/include/limits.h ../../device/include/errno.h
strtoul.rel: strtoul.c ../../device/include/stdlib.h \
 ../../device/include/stdbool.h ../../device/include/ctype.h \
 ../../device/include/string.h ../../device/include/limits.h \
 ../../device/include/errno.h
bsearch.rel: bsearch.c ../../device/include/stdlib.h
qsort.rel: qsort.c ../../device/include/stdlib.h
abs.rel: abs.c ../../device/include/stdlib.h
labs.rel: labs.c ../../device/include/stdlib.h
rand.rel: rand.c ../../device/include/stdlib.h \
 ../../device/include/stdint.h
_strcat.rel: _strcat.c ../../device/include/string.h
_strchr.rel: _strchr.c ../../device/include/string.h
_strcspn.rel: _strcspn.c ../../device/include/string.h
strdup.rel: strdup.c ../../device/include/string.h \
 ../../device/include/stdlib.h
strndup.rel: strndup.c ../../device/include/string.h \
 ../../device/include/stdlib.h
_strncat.rel: _strncat.c ../../device/include/string.h
_strncmp.rel: _strncmp.c ../../device/include/string.h
strxfrm.rel: strxfrm.c ../../device/include/string.h
_strncpy.rel: _strncpy.c ../../device/include/string.h
_strpbrk.rel: _strpbrk.c ../../device/include/string.h
_strrchr.rel: _strrchr.c ../../device/include/string.h
_strspn.rel: _strspn.c ../../device/include/string.h
_strstr.rel: _strstr.c ../../device/include/string.h
_strtok.rel: _strtok.c ../../device/include/string.h
memccpy.rel: memccpy.c ../../device/include/string.h
_memchr.rel: _memchr.c ../../device/include/string.h
_memcmp.rel: _memcmp.c ../../device/include/string.h
_memset.rel: _memset.c ../../device/include/string.h
aligned_alloc.rel: aligned_alloc.c ../../device/include/stddef.h \
 ../../device/include/stdlib.h
calloc.rel: calloc.c ../../device/include/stdlib.h \
 ../../device/include/string.h ../../device/include/stdint.h
malloc.rel: malloc.c ../../device/include/stdlib.h \
 ../../device/include/stddef.h
realloc.rel: realloc.c ../../device/include/stdlib.h \
 ../../device/include/stddef.h ../../device/include/string.h
free.rel: free.c ../../device/include/stdlib.h \
 ../../device/include/stddef.h
mblen.rel: mblen.c ../../device/include/stdlib.h
mbtowc.rel: mbtowc.c ../../device/include/stdlib.h
wctomb.rel: wctomb.c ../../device/include/stdlib.h
mbstowcs.rel: mbstowcs.c ../../device/include/stdlib.h \
 ../../device/include/limits.h
wcstombs.rel: wcstombs.c ../../device/include/stdlib.h \
 ../../device/include/limits.h
mbrtoc16.rel: mbrtoc16.c ../../device/include/uchar.h \
 ../../device/include/limits.h ../../device/include/wchar.h
c16rtomb.rel: c16rtomb.c ../../device/include/uchar.h \
 ../../device/include/stdlib.h ../../device/include/limits.h \
 ../../device/include/errno.h
mbrtoc32.rel: mbrtoc32.c ../../device/include/uchar.h \
 ../../device/include/limits.h ../../device/include/wchar.h
c32rtomb.rel: c32rtomb.c ../../device/include/uchar.h \
 ../../device/include/stdlib.h
mbstoc16s.rel: mbstoc16s.c ../../device/include/uchar.h \
 ../../device/include/stdlib.h ../../device/include/limits.h \
 ../../device/include/wchar.h
c16stombs.rel: c16stombs.c ../../device/include/uchar.h \
 ../../device/include/stdlib.h ../../device/include/string.h \
 ../../device/include/limits.h ../../device/include/wchar.h
wcscmp.rel: wcscmp.c ../../device/include/wchar.h
wcslen.rel: wcslen.c ../../device/include/wchar.h
btowc.rel: btowc.c ../../device/include/wchar.h \
 ../../device/include/stdio.h ../../device/include/stdarg.h \
 ../../device/include/sdcc-lib.h \
 ../../device/include/asm/default/features.h
wctob.rel: wctob.c ../../device/include/wchar.h \
 ../../device/include/stdio.h ../../device/include/stdarg.h \
 ../../device/include/sdcc-lib.h \
 ../../device/include/asm/default/features.h
mbsinit.rel: mbsinit.c ../../device/include/wchar.h
mbrlen.rel: mbrlen.c ../../device/include/wchar.h
mbrtowc.rel: mbrtowc.c ../../device/include/wchar.h \
 ../../device/include/errno.h
wcrtomb.rel: wcrtomb.c ../../device/include/wchar.h \
 ../../device/include/stdlib.h ../../device/include/errno.h
printf_large.rel: printf_large.c ../../device/include/stdarg.h \
 ../../device/include/string.h ../../device/include/ctype.h \
 ../../device/include/stdio.h ../../device/include/sdcc-lib.h \
 ../../device/include/asm/default/features.h \
 ../../device/include/stdbool.h
puts.rel: puts.c ../../device/include/stdio.h \
 ../../device/include/stdarg.h ../../device/include/sdcc-lib.h \
 ../../device/include/asm/default/features.h
gets.rel: gets.c ../../device/include/stdio.h \
 ../../device/include/stdarg.h ../../device/include/sdcc-lib.h \
 ../../device/include/asm/default/features.h
__assert.rel: __assert.c ../../device/include/stdio.h \
 ../../device/include/stdarg.h ../../device/include/sdcc-lib.h \
 ../../device/include/asm/default/features.h \
 ../../device/include/stdlib.h
time.rel: time.c ../../device/include/stdio.h \
 ../../device/include/stdarg.h ../../device/include/sdcc-lib.h \
 ../../device/include/asm/default/features.h ../../device/include/time.h
_autobaud.rel: _autobaud.c ../../device/include/mcs51/8051.h
_bp.rel: _bp.c
_decdptr.rel: _decdptr.c
_gptrget.rel: _gptrget.c
_gptrgetc.rel: _gptrgetc.c
_gptrput.rel: _gptrput.c
_ser.rel: _ser.c ../../device/include/mcs51/8052.h \
 ../../device/include/mcs51/8051.h ../../device/include/mcs51/ser.h
_setjmp.rel: _setjmp.c ../../device/include/sdcc-lib.h \
 ../../device/include/asm/default/features.h \
 ../../device/include/setjmp.h ../../device/include/mcs51/8051.h
serial.rel: serial.c ../../device/include/mcs51/8052.h \
 ../../device/include/mcs51/8051.h
_itoa.rel: _itoa.c
_ltoa.rel: _ltoa.c
_spx.rel: _spx.c
_startup.rel: _startup.c
_strcmp.rel: _strcmp.c ../../device/include/string.h \
 ../../device/include/sdcc-lib.h \
 ../../device/include/asm/default/features.h
_strlen.rel: _strlen.c ../../device/include/string.h
__memcpy.rel: __memcpy.c ../../device/include/string.h
memcpy.rel: memcpy.c ../../device/include/string.h
_memmove.rel: _memmove.c ../../device/include/string.h \
 ../../device/include/stdint.h ../../device/include/sdcc-lib.h \
 ../../device/include/asm/default/features.h
_strcpy.rel: _strcpy.c ../../device/include/string.h \
 ../../device/include/sdcc-lib.h \
 ../../device/include/asm/default/features.h
_heap.rel: _heap.c
sprintf.rel: sprintf.c ../../device/include/stdarg.h \
 ../../device/include/stdio.h ../../device/include/sdcc-lib.h \
 ../../device/include/asm/default/features.h
vprintf.rel: vprintf.c ../../device/include/stdarg.h \
 ../../device/include/stdio.h ../../device/include/sdcc-lib.h \
 ../../device/include/asm/default/features.h
printf_fast.rel: printf_fast.c
printf_fast_f.rel: printf_fast_f.c ../../device/include/float.h \
 ../../device/include/limits.h
printf_tiny.rel: printf_tiny.c
printfl.rel: printfl.c ../../device/include/stdarg.h \
 ../../device/include/stdio.h ../../device/include/sdcc-lib.h \
 ../../device/include/asm/default/features.h \
 ../../device/include/stdlib.h
bpx.rel: bpx.c
