arith.o: arith.cc ../ddconfig.h uc51cl.h ../pobjcl.h ../ddconfig.h \
 ../pobjt.h ../eventcl.h ../charscl.h ../sim.src/simcl.h \
 ../cmd.src/newcmdcl.h ../optioncl.h ../pobjcl.h ../stypes.h \
 ../cmd.src/commandcl.h ../cmd.src/newcmdcl.h ../gui.src/guicl.h \
 ../gui.src/ifcl.h ../sim.src/guiobjcl.h ../sim.src/uccl.h ../stypes.h \
 ../pobjt.h ../sim.src/hwcl.h ../sim.src/guiobjcl.h \
 ../cmd.src/newcmdposixcl.h ../fiocl.h ../cmd.src/cmdutil.h \
 ../sim.src/memcl.h ../eventcl.h ../errorcl.h ../sim.src/brkcl.h \
 ../sim.src/stackcl.h ../sim.src/varcl.h ../sim.src/uccl_instructions.h \
 ../sim.src/argcl.h ../sim.src/memcl.h ../sim.src/uccl.h \
 ../sim.src/itsrccl.h ../sim.src/brkcl.h interruptcl.h regs51.h types51.h
bit.o: bit.cc ../ddconfig.h uc51cl.h ../pobjcl.h ../ddconfig.h ../pobjt.h \
 ../eventcl.h ../charscl.h ../sim.src/simcl.h ../cmd.src/newcmdcl.h \
 ../optioncl.h ../pobjcl.h ../stypes.h ../cmd.src/commandcl.h \
 ../cmd.src/newcmdcl.h ../gui.src/guicl.h ../gui.src/ifcl.h \
 ../sim.src/guiobjcl.h ../sim.src/uccl.h ../stypes.h ../pobjt.h \
 ../sim.src/hwcl.h ../sim.src/guiobjcl.h ../cmd.src/newcmdposixcl.h \
 ../fiocl.h ../cmd.src/cmdutil.h ../sim.src/memcl.h ../eventcl.h \
 ../errorcl.h ../sim.src/brkcl.h ../sim.src/stackcl.h ../sim.src/varcl.h \
 ../sim.src/uccl_instructions.h ../sim.src/argcl.h ../sim.src/memcl.h \
 ../sim.src/uccl.h ../sim.src/itsrccl.h ../sim.src/brkcl.h interruptcl.h \
 regs51.h types51.h
sim51.o: sim51.cc ../ddconfig.h ../i_string.h ../ddconfig.h ../globals.h \
 ../stypes.h ../appcl.h ../pobjcl.h ../pobjt.h ../eventcl.h ../charscl.h \
 ../optioncl.h ../sim.src/argcl.h ../pobjcl.h ../stypes.h \
 ../sim.src/simcl.h ../cmd.src/newcmdcl.h ../optioncl.h \
 ../cmd.src/commandcl.h ../cmd.src/newcmdcl.h ../gui.src/guicl.h \
 ../gui.src/ifcl.h ../sim.src/guiobjcl.h ../sim.src/uccl.h ../pobjt.h \
 ../sim.src/hwcl.h ../sim.src/guiobjcl.h ../cmd.src/newcmdposixcl.h \
 ../fiocl.h ../cmd.src/cmdutil.h ../sim.src/memcl.h ../eventcl.h \
 ../errorcl.h ../sim.src/brkcl.h ../sim.src/stackcl.h ../sim.src/varcl.h \
 ../sim.src/uccl_instructions.h ../sim.src/argcl.h ../utils.h ../fiocl.h \
 ../cmd.src/cmdutil.h ../charscl.h sim51cl.h uc51cl.h ../sim.src/memcl.h \
 ../sim.src/uccl.h ../sim.src/itsrccl.h ../sim.src/brkcl.h interruptcl.h \
 uc52cl.h uc521cl.h uc517cl.h uc51rcl.h uc89c51rcl.h uc251cl.h uc390cl.h \
 uc88xcl.h uc320cl.h uc380cl.h glob.h
uc89c51r.o: uc89c51r.cc ../ddconfig.h uc89c51rcl.h uc51rcl.h uc52cl.h \
 uc51cl.h ../pobjcl.h ../ddconfig.h ../pobjt.h ../eventcl.h ../charscl.h \
 ../sim.src/simcl.h ../cmd.src/newcmdcl.h ../optioncl.h ../pobjcl.h \
 ../stypes.h ../cmd.src/commandcl.h ../cmd.src/newcmdcl.h \
 ../gui.src/guicl.h ../gui.src/ifcl.h ../sim.src/guiobjcl.h \
 ../sim.src/uccl.h ../stypes.h ../pobjt.h ../sim.src/hwcl.h \
 ../sim.src/guiobjcl.h ../cmd.src/newcmdposixcl.h ../fiocl.h \
 ../cmd.src/cmdutil.h ../sim.src/memcl.h ../eventcl.h ../errorcl.h \
 ../sim.src/brkcl.h ../sim.src/stackcl.h ../sim.src/varcl.h \
 ../sim.src/uccl_instructions.h ../sim.src/argcl.h ../sim.src/memcl.h \
 ../sim.src/uccl.h ../sim.src/itsrccl.h ../sim.src/brkcl.h interruptcl.h \
 regs51.h pcacl.h wdtcl.h
timer2.o: timer2.cc timer2cl.h ../stypes.h ../ddconfig.h ../pobjcl.h \
 ../pobjt.h ../eventcl.h ../charscl.h ../sim.src/uccl.h ../pobjt.h \
 ../sim.src/hwcl.h ../sim.src/guiobjcl.h ../ddconfig.h \
 ../cmd.src/newcmdcl.h ../optioncl.h ../pobjcl.h ../stypes.h \
 ../cmd.src/commandcl.h ../cmd.src/newcmdcl.h ../cmd.src/newcmdposixcl.h \
 ../fiocl.h ../cmd.src/cmdutil.h ../sim.src/memcl.h ../eventcl.h \
 ../errorcl.h ../sim.src/uccl.h ../sim.src/brkcl.h ../sim.src/stackcl.h \
 ../sim.src/varcl.h ../sim.src/uccl_instructions.h timer0cl.h uc51cl.h \
 ../sim.src/simcl.h ../gui.src/guicl.h ../gui.src/ifcl.h \
 ../sim.src/guiobjcl.h ../sim.src/argcl.h ../sim.src/memcl.h \
 ../sim.src/itsrccl.h ../sim.src/brkcl.h interruptcl.h regs51.h types51.h
uc390.o: uc390.cc ../ddconfig.h ../i_string.h ../ddconfig.h glob.h \
 uc390cl.h uc52cl.h uc51cl.h ../pobjcl.h ../pobjt.h ../eventcl.h \
 ../charscl.h ../sim.src/simcl.h ../cmd.src/newcmdcl.h ../optioncl.h \
 ../pobjcl.h ../stypes.h ../cmd.src/commandcl.h ../cmd.src/newcmdcl.h \
 ../gui.src/guicl.h ../gui.src/ifcl.h ../sim.src/guiobjcl.h \
 ../sim.src/uccl.h ../stypes.h ../pobjt.h ../sim.src/hwcl.h \
 ../sim.src/guiobjcl.h ../cmd.src/newcmdposixcl.h ../fiocl.h \
 ../cmd.src/cmdutil.h ../sim.src/memcl.h ../eventcl.h ../errorcl.h \
 ../sim.src/brkcl.h ../sim.src/stackcl.h ../sim.src/varcl.h \
 ../sim.src/uccl_instructions.h ../sim.src/argcl.h ../sim.src/memcl.h \
 ../sim.src/uccl.h ../sim.src/itsrccl.h ../sim.src/brkcl.h interruptcl.h \
 regs51.h uc390hwcl.h timer2cl.h timer0cl.h
uc380.o: uc380.cc portcl.h ../stypes.h ../ddconfig.h ../pobjcl.h \
 ../pobjt.h ../eventcl.h ../charscl.h ../sim.src/uccl.h ../pobjt.h \
 ../sim.src/hwcl.h ../sim.src/guiobjcl.h ../ddconfig.h \
 ../cmd.src/newcmdcl.h ../optioncl.h ../pobjcl.h ../stypes.h \
 ../cmd.src/commandcl.h ../cmd.src/newcmdcl.h ../cmd.src/newcmdposixcl.h \
 ../fiocl.h ../cmd.src/cmdutil.h ../sim.src/memcl.h ../eventcl.h \
 ../errorcl.h ../sim.src/uccl.h ../sim.src/brkcl.h ../sim.src/stackcl.h \
 ../sim.src/varcl.h ../sim.src/uccl_instructions.h ../sim.src/port_hwcl.h \
 uc380cl.h uc52cl.h uc51cl.h ../sim.src/simcl.h ../gui.src/guicl.h \
 ../gui.src/ifcl.h ../sim.src/guiobjcl.h ../sim.src/argcl.h \
 ../sim.src/memcl.h ../sim.src/itsrccl.h ../sim.src/brkcl.h interruptcl.h
uc51.o: uc51.cc ../ddconfig.h ../i_string.h ../ddconfig.h ../utils.h \
 ../stypes.h ../charscl.h ../fiocl.h ../pobjcl.h ../pobjt.h ../eventcl.h \
 ../globals.h ../appcl.h ../optioncl.h ../sim.src/argcl.h ../pobjcl.h \
 ../stypes.h ../sim.src/simcl.h ../cmd.src/newcmdcl.h ../optioncl.h \
 ../cmd.src/commandcl.h ../cmd.src/newcmdcl.h ../gui.src/guicl.h \
 ../gui.src/ifcl.h ../sim.src/guiobjcl.h ../sim.src/uccl.h ../pobjt.h \
 ../sim.src/hwcl.h ../sim.src/guiobjcl.h ../cmd.src/newcmdposixcl.h \
 ../fiocl.h ../cmd.src/cmdutil.h ../sim.src/memcl.h ../eventcl.h \
 ../errorcl.h ../sim.src/brkcl.h ../sim.src/stackcl.h ../sim.src/varcl.h \
 ../sim.src/uccl_instructions.h ../sim.src/argcl.h ../sim.src/iwrap.h \
 ../cmd.src/cmd_uccl.h uc51cl.h ../sim.src/memcl.h ../sim.src/uccl.h \
 ../sim.src/itsrccl.h ../sim.src/brkcl.h interruptcl.h glob.h regs51.h \
 timer0cl.h timer1cl.h serialcl.h ../sim.src/serial_hwcl.h portcl.h \
 ../sim.src/port_hwcl.h types51.h
interrupt.o: interrupt.cc ../utils.h ../stypes.h ../ddconfig.h \
 ../charscl.h ../fiocl.h ../pobjcl.h ../pobjt.h ../eventcl.h \
 ../sim.src/itsrccl.h ../pobjcl.h ../stypes.h ../sim.src/uccl.h \
 ../pobjt.h ../sim.src/hwcl.h ../sim.src/guiobjcl.h ../ddconfig.h \
 ../cmd.src/newcmdcl.h ../optioncl.h ../cmd.src/commandcl.h \
 ../cmd.src/newcmdcl.h ../cmd.src/newcmdposixcl.h ../fiocl.h \
 ../cmd.src/cmdutil.h ../sim.src/memcl.h ../eventcl.h ../errorcl.h \
 ../sim.src/brkcl.h ../sim.src/stackcl.h ../sim.src/varcl.h \
 ../sim.src/uccl_instructions.h interruptcl.h ../sim.src/uccl.h regs51.h \
 types51.h
inc.o: inc.cc ../ddconfig.h uc51cl.h ../pobjcl.h ../ddconfig.h ../pobjt.h \
 ../eventcl.h ../charscl.h ../sim.src/simcl.h ../cmd.src/newcmdcl.h \
 ../optioncl.h ../pobjcl.h ../stypes.h ../cmd.src/commandcl.h \
 ../cmd.src/newcmdcl.h ../gui.src/guicl.h ../gui.src/ifcl.h \
 ../sim.src/guiobjcl.h ../sim.src/uccl.h ../stypes.h ../pobjt.h \
 ../sim.src/hwcl.h ../sim.src/guiobjcl.h ../cmd.src/newcmdposixcl.h \
 ../fiocl.h ../cmd.src/cmdutil.h ../sim.src/memcl.h ../eventcl.h \
 ../errorcl.h ../sim.src/brkcl.h ../sim.src/stackcl.h ../sim.src/varcl.h \
 ../sim.src/uccl_instructions.h ../sim.src/argcl.h ../sim.src/memcl.h \
 ../sim.src/uccl.h ../sim.src/itsrccl.h ../sim.src/brkcl.h interruptcl.h \
 regs51.h
uc390hw.o: uc390hw.cc ../ddconfig.h uc390hwcl.h ../sim.src/uccl.h \
 ../stypes.h ../ddconfig.h ../pobjcl.h ../pobjt.h ../eventcl.h \
 ../charscl.h ../pobjt.h ../sim.src/hwcl.h ../sim.src/guiobjcl.h \
 ../cmd.src/newcmdcl.h ../optioncl.h ../pobjcl.h ../stypes.h \
 ../cmd.src/commandcl.h ../cmd.src/newcmdcl.h ../cmd.src/newcmdposixcl.h \
 ../fiocl.h ../cmd.src/cmdutil.h ../sim.src/memcl.h ../eventcl.h \
 ../errorcl.h ../sim.src/uccl.h ../sim.src/brkcl.h ../sim.src/stackcl.h \
 ../sim.src/varcl.h ../sim.src/uccl_instructions.h uc390cl.h uc52cl.h \
 uc51cl.h ../sim.src/simcl.h ../gui.src/guicl.h ../gui.src/ifcl.h \
 ../sim.src/guiobjcl.h ../sim.src/argcl.h ../sim.src/memcl.h \
 ../sim.src/itsrccl.h ../sim.src/brkcl.h interruptcl.h regs51.h
jmp.o: jmp.cc ../ddconfig.h uc51cl.h ../pobjcl.h ../ddconfig.h ../pobjt.h \
 ../eventcl.h ../charscl.h ../sim.src/simcl.h ../cmd.src/newcmdcl.h \
 ../optioncl.h ../pobjcl.h ../stypes.h ../cmd.src/commandcl.h \
 ../cmd.src/newcmdcl.h ../gui.src/guicl.h ../gui.src/ifcl.h \
 ../sim.src/guiobjcl.h ../sim.src/uccl.h ../stypes.h ../pobjt.h \
 ../sim.src/hwcl.h ../sim.src/guiobjcl.h ../cmd.src/newcmdposixcl.h \
 ../fiocl.h ../cmd.src/cmdutil.h ../sim.src/memcl.h ../eventcl.h \
 ../errorcl.h ../sim.src/brkcl.h ../sim.src/stackcl.h ../sim.src/varcl.h \
 ../sim.src/uccl_instructions.h ../sim.src/argcl.h ../sim.src/memcl.h \
 ../sim.src/uccl.h ../sim.src/itsrccl.h ../sim.src/brkcl.h interruptcl.h \
 regs51.h types51.h
mov.o: mov.cc ../ddconfig.h ../sim.src/memcl.h ../stypes.h ../ddconfig.h \
 ../pobjcl.h ../pobjt.h ../eventcl.h ../charscl.h ../sim.src/guiobjcl.h \
 ../eventcl.h ../errorcl.h ../pobjcl.h ../stypes.h uc51cl.h \
 ../sim.src/simcl.h ../cmd.src/newcmdcl.h ../optioncl.h \
 ../cmd.src/commandcl.h ../cmd.src/newcmdcl.h ../gui.src/guicl.h \
 ../gui.src/ifcl.h ../sim.src/guiobjcl.h ../sim.src/uccl.h ../pobjt.h \
 ../sim.src/hwcl.h ../cmd.src/newcmdposixcl.h ../fiocl.h \
 ../cmd.src/cmdutil.h ../sim.src/memcl.h ../sim.src/brkcl.h \
 ../sim.src/stackcl.h ../sim.src/varcl.h ../sim.src/uccl_instructions.h \
 ../sim.src/argcl.h ../sim.src/uccl.h ../sim.src/itsrccl.h \
 ../sim.src/brkcl.h interruptcl.h regs51.h
uc251.o: uc251.cc ../ddconfig.h uc251cl.h uc89c51rcl.h uc51rcl.h uc52cl.h \
 uc51cl.h ../pobjcl.h ../ddconfig.h ../pobjt.h ../eventcl.h ../charscl.h \
 ../sim.src/simcl.h ../cmd.src/newcmdcl.h ../optioncl.h ../pobjcl.h \
 ../stypes.h ../cmd.src/commandcl.h ../cmd.src/newcmdcl.h \
 ../gui.src/guicl.h ../gui.src/ifcl.h ../sim.src/guiobjcl.h \
 ../sim.src/uccl.h ../stypes.h ../pobjt.h ../sim.src/hwcl.h \
 ../sim.src/guiobjcl.h ../cmd.src/newcmdposixcl.h ../fiocl.h \
 ../cmd.src/cmdutil.h ../sim.src/memcl.h ../eventcl.h ../errorcl.h \
 ../sim.src/brkcl.h ../sim.src/stackcl.h ../sim.src/varcl.h \
 ../sim.src/uccl_instructions.h ../sim.src/argcl.h ../sim.src/memcl.h \
 ../sim.src/uccl.h ../sim.src/itsrccl.h ../sim.src/brkcl.h interruptcl.h
uc52.o: uc52.cc ../ddconfig.h uc52cl.h uc51cl.h ../pobjcl.h ../ddconfig.h \
 ../pobjt.h ../eventcl.h ../charscl.h ../sim.src/simcl.h \
 ../cmd.src/newcmdcl.h ../optioncl.h ../pobjcl.h ../stypes.h \
 ../cmd.src/commandcl.h ../cmd.src/newcmdcl.h ../gui.src/guicl.h \
 ../gui.src/ifcl.h ../sim.src/guiobjcl.h ../sim.src/uccl.h ../stypes.h \
 ../pobjt.h ../sim.src/hwcl.h ../sim.src/guiobjcl.h \
 ../cmd.src/newcmdposixcl.h ../fiocl.h ../cmd.src/cmdutil.h \
 ../sim.src/memcl.h ../eventcl.h ../errorcl.h ../sim.src/brkcl.h \
 ../sim.src/stackcl.h ../sim.src/varcl.h ../sim.src/uccl_instructions.h \
 ../sim.src/argcl.h ../sim.src/memcl.h ../sim.src/uccl.h \
 ../sim.src/itsrccl.h ../sim.src/brkcl.h interruptcl.h regs51.h \
 timer2cl.h timer0cl.h portcl.h ../sim.src/port_hwcl.h mducl.h \
 ../sim.src/hwcl.h
mdu.o: mdu.cc uc51cl.h ../pobjcl.h ../ddconfig.h ../pobjt.h ../eventcl.h \
 ../charscl.h ../sim.src/simcl.h ../cmd.src/newcmdcl.h ../ddconfig.h \
 ../optioncl.h ../pobjcl.h ../stypes.h ../cmd.src/commandcl.h \
 ../cmd.src/newcmdcl.h ../gui.src/guicl.h ../gui.src/ifcl.h \
 ../sim.src/guiobjcl.h ../sim.src/uccl.h ../stypes.h ../pobjt.h \
 ../sim.src/hwcl.h ../sim.src/guiobjcl.h ../cmd.src/newcmdposixcl.h \
 ../fiocl.h ../cmd.src/cmdutil.h ../sim.src/memcl.h ../eventcl.h \
 ../errorcl.h ../sim.src/brkcl.h ../sim.src/stackcl.h ../sim.src/varcl.h \
 ../sim.src/uccl_instructions.h ../sim.src/argcl.h ../sim.src/memcl.h \
 ../sim.src/uccl.h ../sim.src/itsrccl.h ../sim.src/brkcl.h interruptcl.h \
 mducl.h ../sim.src/hwcl.h
logic.o: logic.cc ../ddconfig.h ../stypes.h ../ddconfig.h uc51cl.h \
 ../pobjcl.h ../pobjt.h ../eventcl.h ../charscl.h ../sim.src/simcl.h \
 ../cmd.src/newcmdcl.h ../optioncl.h ../pobjcl.h ../stypes.h \
 ../cmd.src/commandcl.h ../cmd.src/newcmdcl.h ../gui.src/guicl.h \
 ../gui.src/ifcl.h ../sim.src/guiobjcl.h ../sim.src/uccl.h ../pobjt.h \
 ../sim.src/hwcl.h ../sim.src/guiobjcl.h ../cmd.src/newcmdposixcl.h \
 ../fiocl.h ../cmd.src/cmdutil.h ../sim.src/memcl.h ../eventcl.h \
 ../errorcl.h ../sim.src/brkcl.h ../sim.src/stackcl.h ../sim.src/varcl.h \
 ../sim.src/uccl_instructions.h ../sim.src/argcl.h ../sim.src/memcl.h \
 ../sim.src/uccl.h ../sim.src/itsrccl.h ../sim.src/brkcl.h interruptcl.h \
 regs51.h
serial.o: serial.cc ../ddconfig.h ../globals.h ../ddconfig.h ../stypes.h \
 ../appcl.h ../pobjcl.h ../pobjt.h ../eventcl.h ../charscl.h \
 ../optioncl.h ../sim.src/argcl.h ../pobjcl.h ../stypes.h \
 ../sim.src/simcl.h ../cmd.src/newcmdcl.h ../optioncl.h \
 ../cmd.src/commandcl.h ../cmd.src/newcmdcl.h ../gui.src/guicl.h \
 ../gui.src/ifcl.h ../sim.src/guiobjcl.h ../sim.src/uccl.h ../pobjt.h \
 ../sim.src/hwcl.h ../sim.src/guiobjcl.h ../cmd.src/newcmdposixcl.h \
 ../fiocl.h ../cmd.src/cmdutil.h ../sim.src/memcl.h ../eventcl.h \
 ../errorcl.h ../sim.src/brkcl.h ../sim.src/stackcl.h ../sim.src/varcl.h \
 ../sim.src/uccl_instructions.h ../sim.src/argcl.h ../utils.h ../fiocl.h \
 ../cmd.src/cmdutil.h serialcl.h ../sim.src/uccl.h \
 ../sim.src/serial_hwcl.h regs51.h uc51cl.h ../sim.src/memcl.h \
 ../sim.src/itsrccl.h ../sim.src/brkcl.h interruptcl.h
uc521.o: uc521.cc uc521cl.h uc52cl.h ../ddconfig.h uc51cl.h ../pobjcl.h \
 ../ddconfig.h ../pobjt.h ../eventcl.h ../charscl.h ../sim.src/simcl.h \
 ../cmd.src/newcmdcl.h ../optioncl.h ../pobjcl.h ../stypes.h \
 ../cmd.src/commandcl.h ../cmd.src/newcmdcl.h ../gui.src/guicl.h \
 ../gui.src/ifcl.h ../sim.src/guiobjcl.h ../sim.src/uccl.h ../stypes.h \
 ../pobjt.h ../sim.src/hwcl.h ../sim.src/guiobjcl.h \
 ../cmd.src/newcmdposixcl.h ../fiocl.h ../cmd.src/cmdutil.h \
 ../sim.src/memcl.h ../eventcl.h ../errorcl.h ../sim.src/brkcl.h \
 ../sim.src/stackcl.h ../sim.src/varcl.h ../sim.src/uccl_instructions.h \
 ../sim.src/argcl.h ../sim.src/memcl.h ../sim.src/uccl.h \
 ../sim.src/itsrccl.h ../sim.src/brkcl.h interruptcl.h
uc320.o: uc320.cc ../ddconfig.h ../i_string.h ../ddconfig.h glob.h \
 uc320cl.h uc521cl.h uc52cl.h uc51cl.h ../pobjcl.h ../pobjt.h \
 ../eventcl.h ../charscl.h ../sim.src/simcl.h ../cmd.src/newcmdcl.h \
 ../optioncl.h ../pobjcl.h ../stypes.h ../cmd.src/commandcl.h \
 ../cmd.src/newcmdcl.h ../gui.src/guicl.h ../gui.src/ifcl.h \
 ../sim.src/guiobjcl.h ../sim.src/uccl.h ../stypes.h ../pobjt.h \
 ../sim.src/hwcl.h ../sim.src/guiobjcl.h ../cmd.src/newcmdposixcl.h \
 ../fiocl.h ../cmd.src/cmdutil.h ../sim.src/memcl.h ../eventcl.h \
 ../errorcl.h ../sim.src/brkcl.h ../sim.src/stackcl.h ../sim.src/varcl.h \
 ../sim.src/uccl_instructions.h ../sim.src/argcl.h ../sim.src/memcl.h \
 ../sim.src/uccl.h ../sim.src/itsrccl.h ../sim.src/brkcl.h interruptcl.h \
 regs51.h
glob.o: glob.cc ../stypes.h ../ddconfig.h
pca.o: pca.cc ../sim.src/itsrccl.h ../pobjcl.h ../ddconfig.h ../pobjt.h \
 ../eventcl.h ../charscl.h ../stypes.h ../sim.src/uccl.h ../pobjt.h \
 ../sim.src/hwcl.h ../sim.src/guiobjcl.h ../ddconfig.h \
 ../cmd.src/newcmdcl.h ../optioncl.h ../pobjcl.h ../stypes.h \
 ../cmd.src/commandcl.h ../cmd.src/newcmdcl.h ../cmd.src/newcmdposixcl.h \
 ../fiocl.h ../cmd.src/cmdutil.h ../sim.src/memcl.h ../eventcl.h \
 ../errorcl.h ../sim.src/brkcl.h ../sim.src/stackcl.h ../sim.src/varcl.h \
 ../sim.src/uccl_instructions.h pcacl.h ../sim.src/uccl.h regs51.h \
 types51.h
uc51r.o: uc51r.cc ../ddconfig.h uc51rcl.h uc52cl.h uc51cl.h ../pobjcl.h \
 ../ddconfig.h ../pobjt.h ../eventcl.h ../charscl.h ../sim.src/simcl.h \
 ../cmd.src/newcmdcl.h ../optioncl.h ../pobjcl.h ../stypes.h \
 ../cmd.src/commandcl.h ../cmd.src/newcmdcl.h ../gui.src/guicl.h \
 ../gui.src/ifcl.h ../sim.src/guiobjcl.h ../sim.src/uccl.h ../stypes.h \
 ../pobjt.h ../sim.src/hwcl.h ../sim.src/guiobjcl.h \
 ../cmd.src/newcmdposixcl.h ../fiocl.h ../cmd.src/cmdutil.h \
 ../sim.src/memcl.h ../eventcl.h ../errorcl.h ../sim.src/brkcl.h \
 ../sim.src/stackcl.h ../sim.src/varcl.h ../sim.src/uccl_instructions.h \
 ../sim.src/argcl.h ../sim.src/memcl.h ../sim.src/uccl.h \
 ../sim.src/itsrccl.h ../sim.src/brkcl.h interruptcl.h regs51.h types51.h \
 wdtcl.h
port.o: port.cc ../sim.src/argcl.h ../pobjcl.h ../ddconfig.h ../pobjt.h \
 ../eventcl.h ../charscl.h ../stypes.h regs51.h types51.h ../ddconfig.h \
 portcl.h ../sim.src/uccl.h ../pobjt.h ../sim.src/hwcl.h \
 ../sim.src/guiobjcl.h ../cmd.src/newcmdcl.h ../optioncl.h ../pobjcl.h \
 ../stypes.h ../cmd.src/commandcl.h ../cmd.src/newcmdcl.h \
 ../cmd.src/newcmdposixcl.h ../fiocl.h ../cmd.src/cmdutil.h \
 ../sim.src/memcl.h ../eventcl.h ../errorcl.h ../sim.src/uccl.h \
 ../sim.src/brkcl.h ../sim.src/stackcl.h ../sim.src/varcl.h \
 ../sim.src/uccl_instructions.h ../sim.src/port_hwcl.h
wdt.o: wdt.cc wdtcl.h ../sim.src/uccl.h ../stypes.h ../ddconfig.h \
 ../pobjcl.h ../pobjt.h ../eventcl.h ../charscl.h ../pobjt.h \
 ../sim.src/hwcl.h ../sim.src/guiobjcl.h ../ddconfig.h \
 ../cmd.src/newcmdcl.h ../optioncl.h ../pobjcl.h ../stypes.h \
 ../cmd.src/commandcl.h ../cmd.src/newcmdcl.h ../cmd.src/newcmdposixcl.h \
 ../fiocl.h ../cmd.src/cmdutil.h ../sim.src/memcl.h ../eventcl.h \
 ../errorcl.h ../sim.src/uccl.h ../sim.src/brkcl.h ../sim.src/stackcl.h \
 ../sim.src/varcl.h ../sim.src/uccl_instructions.h uc51rcl.h uc52cl.h \
 uc51cl.h ../sim.src/simcl.h ../gui.src/guicl.h ../gui.src/ifcl.h \
 ../sim.src/guiobjcl.h ../sim.src/argcl.h ../sim.src/memcl.h \
 ../sim.src/itsrccl.h ../sim.src/brkcl.h interruptcl.h regs51.h
uc517.o: uc517.cc mducl.h ../sim.src/hwcl.h ../stypes.h ../ddconfig.h \
 ../pobjcl.h ../pobjt.h ../eventcl.h ../charscl.h ../sim.src/guiobjcl.h \
 ../ddconfig.h ../cmd.src/newcmdcl.h ../optioncl.h ../pobjcl.h \
 ../stypes.h ../cmd.src/commandcl.h ../cmd.src/newcmdcl.h \
 ../cmd.src/newcmdposixcl.h ../fiocl.h ../cmd.src/cmdutil.h \
 ../sim.src/memcl.h ../eventcl.h ../errorcl.h ../sim.src/uccl.h \
 ../pobjt.h ../sim.src/hwcl.h ../sim.src/brkcl.h ../sim.src/stackcl.h \
 ../sim.src/varcl.h ../sim.src/uccl_instructions.h uc517cl.h uc52cl.h \
 uc51cl.h ../sim.src/simcl.h ../gui.src/guicl.h ../gui.src/ifcl.h \
 ../sim.src/guiobjcl.h ../sim.src/argcl.h ../sim.src/memcl.h \
 ../sim.src/uccl.h ../sim.src/itsrccl.h ../sim.src/brkcl.h interruptcl.h
s51.o: s51.cc ../ddconfig.h ../globals.h ../ddconfig.h ../stypes.h \
 ../appcl.h ../pobjcl.h ../pobjt.h ../eventcl.h ../charscl.h \
 ../optioncl.h ../sim.src/argcl.h ../pobjcl.h ../stypes.h \
 ../sim.src/simcl.h ../cmd.src/newcmdcl.h ../optioncl.h \
 ../cmd.src/commandcl.h ../cmd.src/newcmdcl.h ../gui.src/guicl.h \
 ../gui.src/ifcl.h ../sim.src/guiobjcl.h ../sim.src/uccl.h ../pobjt.h \
 ../sim.src/hwcl.h ../sim.src/guiobjcl.h ../cmd.src/newcmdposixcl.h \
 ../fiocl.h ../cmd.src/cmdutil.h ../sim.src/memcl.h ../eventcl.h \
 ../errorcl.h ../sim.src/brkcl.h ../sim.src/stackcl.h ../sim.src/varcl.h \
 ../sim.src/uccl_instructions.h ../sim.src/argcl.h ../appcl.h sim51cl.h
uc88x.o: uc88x.cc mducl.h ../sim.src/hwcl.h ../stypes.h ../ddconfig.h \
 ../pobjcl.h ../pobjt.h ../eventcl.h ../charscl.h ../sim.src/guiobjcl.h \
 ../ddconfig.h ../cmd.src/newcmdcl.h ../optioncl.h ../pobjcl.h \
 ../stypes.h ../cmd.src/commandcl.h ../cmd.src/newcmdcl.h \
 ../cmd.src/newcmdposixcl.h ../fiocl.h ../cmd.src/cmdutil.h \
 ../sim.src/memcl.h ../eventcl.h ../errorcl.h ../sim.src/uccl.h \
 ../pobjt.h ../sim.src/hwcl.h ../sim.src/brkcl.h ../sim.src/stackcl.h \
 ../sim.src/varcl.h ../sim.src/uccl_instructions.h uc88xcl.h uc52cl.h \
 uc51cl.h ../sim.src/simcl.h ../gui.src/guicl.h ../gui.src/ifcl.h \
 ../sim.src/guiobjcl.h ../sim.src/argcl.h ../sim.src/memcl.h \
 ../sim.src/uccl.h ../sim.src/itsrccl.h ../sim.src/brkcl.h interruptcl.h
timer0.o: timer0.cc timer0cl.h ../stypes.h ../ddconfig.h ../pobjcl.h \
 ../pobjt.h ../eventcl.h ../charscl.h ../sim.src/uccl.h ../pobjt.h \
 ../sim.src/hwcl.h ../sim.src/guiobjcl.h ../ddconfig.h \
 ../cmd.src/newcmdcl.h ../optioncl.h ../pobjcl.h ../stypes.h \
 ../cmd.src/commandcl.h ../cmd.src/newcmdcl.h ../cmd.src/newcmdposixcl.h \
 ../fiocl.h ../cmd.src/cmdutil.h ../sim.src/memcl.h ../eventcl.h \
 ../errorcl.h ../sim.src/uccl.h ../sim.src/brkcl.h ../sim.src/stackcl.h \
 ../sim.src/varcl.h ../sim.src/uccl_instructions.h uc51cl.h \
 ../sim.src/simcl.h ../gui.src/guicl.h ../gui.src/ifcl.h \
 ../sim.src/guiobjcl.h ../sim.src/argcl.h ../sim.src/memcl.h \
 ../sim.src/itsrccl.h ../sim.src/brkcl.h interruptcl.h regs51.h types51.h
timer1.o: timer1.cc timer1cl.h ../stypes.h ../ddconfig.h ../pobjcl.h \
 ../pobjt.h ../eventcl.h ../charscl.h ../sim.src/uccl.h ../pobjt.h \
 ../sim.src/hwcl.h ../sim.src/guiobjcl.h ../ddconfig.h \
 ../cmd.src/newcmdcl.h ../optioncl.h ../pobjcl.h ../stypes.h \
 ../cmd.src/commandcl.h ../cmd.src/newcmdcl.h ../cmd.src/newcmdposixcl.h \
 ../fiocl.h ../cmd.src/cmdutil.h ../sim.src/memcl.h ../eventcl.h \
 ../errorcl.h ../sim.src/uccl.h ../sim.src/brkcl.h ../sim.src/stackcl.h \
 ../sim.src/varcl.h ../sim.src/uccl_instructions.h timer0cl.h uc51cl.h \
 ../sim.src/simcl.h ../gui.src/guicl.h ../gui.src/ifcl.h \
 ../sim.src/guiobjcl.h ../sim.src/argcl.h ../sim.src/memcl.h \
 ../sim.src/itsrccl.h ../sim.src/brkcl.h interruptcl.h regs51.h
