SDCCy.o: SDCCy.c SDCCglobl.h SDCCset.h ../sdccconf.h SDCCerr.h SDCCsymt.h \
 SDCChasht.h ../support/util/dbuf.h SDCCval.h SDCCmem.h SDCCast.h port.h \
 SDCCicode.h SDCCbitv.h SDCCargs.h SDCCpeeph.h SDCCgen.h SDCCicode.h \
 SDCCbitv.h SDCCset.h SDCCast.h ../support/util/newalloc.h SDCCutil.h \
 SDCCbtree.h SDCCopt.h SDCCBBlock.h
SDCChasht.o: SDCChasht.c SDCCerr.h SDCCglobl.h SDCCset.h ../sdccconf.h \
 SDCChasht.h ../support/util/newalloc.h
SDCCmain.o: SDCCmain.c common.h SDCCglobl.h SDCCset.h ../sdccconf.h \
 SDCCerr.h SDCCmem.h ../support/util/dbuf.h SDCCsymt.h SDCChasht.h \
 SDCCval.h SDCCast.h SDCCy.h SDCCbitv.h SDCCicode.h SDCClabel.h \
 SDCCBBlock.h SDCCloop.h SDCCcse.h SDCCcflow.h SDCCdflow.h SDCClrange.h \
 SDCCptropt.h SDCCopt.h SDCCglue.h SDCCpeeph.h SDCCgen.h SDCCicode.h \
 SDCCbitv.h SDCCset.h SDCCast.h SDCCdebug.h SDCCutil.h SDCCasm.h \
 SDCCsystem.h port.h SDCCargs.h ../support/util/newalloc.h \
 ../support/util/dbuf_string.h ../support/util/dbuf.h SDCCmacro.h
SDCCsymt.o: SDCCsymt.c common.h SDCCglobl.h SDCCset.h ../sdccconf.h \
 SDCCerr.h SDCCmem.h ../support/util/dbuf.h SDCCsymt.h SDCChasht.h \
 SDCCval.h SDCCast.h SDCCy.h SDCCbitv.h SDCCicode.h SDCClabel.h \
 SDCCBBlock.h SDCCloop.h SDCCcse.h SDCCcflow.h SDCCdflow.h SDCClrange.h \
 SDCCptropt.h SDCCopt.h SDCCglue.h SDCCpeeph.h SDCCgen.h SDCCicode.h \
 SDCCbitv.h SDCCset.h SDCCast.h SDCCdebug.h SDCCutil.h SDCCasm.h \
 SDCCsystem.h port.h SDCCargs.h ../support/util/newalloc.h \
 ../support/util/dbuf_string.h ../support/util/dbuf.h
SDCCopt.o: SDCCopt.c common.h SDCCglobl.h SDCCset.h ../sdccconf.h \
 SDCCerr.h SDCCmem.h ../support/util/dbuf.h SDCCsymt.h SDCChasht.h \
 SDCCval.h SDCCast.h SDCCy.h SDCCbitv.h SDCCicode.h SDCClabel.h \
 SDCCBBlock.h SDCCloop.h SDCCcse.h SDCCcflow.h SDCCdflow.h SDCClrange.h \
 SDCCptropt.h SDCCopt.h SDCCglue.h SDCCpeeph.h SDCCgen.h SDCCicode.h \
 SDCCbitv.h SDCCset.h SDCCast.h SDCCdebug.h SDCCutil.h SDCCasm.h \
 SDCCsystem.h port.h SDCCargs.h ../support/util/newalloc.h \
 ../support/util/dbuf_string.h ../support/util/dbuf.h
SDCCast.o: SDCCast.c common.h SDCCglobl.h SDCCset.h ../sdccconf.h \
 SDCCerr.h SDCCmem.h ../support/util/dbuf.h SDCCsymt.h SDCChasht.h \
 SDCCval.h SDCCast.h SDCCy.h SDCCbitv.h SDCCicode.h SDCClabel.h \
 SDCCBBlock.h SDCCloop.h SDCCcse.h SDCCcflow.h SDCCdflow.h SDCClrange.h \
 SDCCptropt.h SDCCopt.h SDCCglue.h SDCCpeeph.h SDCCgen.h SDCCicode.h \
 SDCCbitv.h SDCCset.h SDCCast.h SDCCdebug.h SDCCutil.h SDCCasm.h \
 SDCCsystem.h port.h SDCCargs.h ../support/util/newalloc.h \
 ../support/util/dbuf_string.h ../support/util/dbuf.h SDCCbtree.h
SDCCmem.o: SDCCmem.c common.h SDCCglobl.h SDCCset.h ../sdccconf.h \
 SDCCerr.h SDCCmem.h ../support/util/dbuf.h SDCCsymt.h SDCChasht.h \
 SDCCval.h SDCCast.h SDCCy.h SDCCbitv.h SDCCicode.h SDCClabel.h \
 SDCCBBlock.h SDCCloop.h SDCCcse.h SDCCcflow.h SDCCdflow.h SDCClrange.h \
 SDCCptropt.h SDCCopt.h SDCCglue.h SDCCpeeph.h SDCCgen.h SDCCicode.h \
 SDCCbitv.h SDCCset.h SDCCast.h SDCCdebug.h SDCCutil.h SDCCasm.h \
 SDCCsystem.h port.h SDCCargs.h ../support/util/newalloc.h \
 ../support/util/dbuf_string.h ../support/util/dbuf.h SDCCbtree.h
SDCCval.o: SDCCval.c common.h SDCCglobl.h SDCCset.h ../sdccconf.h \
 SDCCerr.h SDCCmem.h ../support/util/dbuf.h SDCCsymt.h SDCChasht.h \
 SDCCval.h SDCCast.h SDCCy.h SDCCbitv.h SDCCicode.h SDCClabel.h \
 SDCCBBlock.h SDCCloop.h SDCCcse.h SDCCcflow.h SDCCdflow.h SDCClrange.h \
 SDCCptropt.h SDCCopt.h SDCCglue.h SDCCpeeph.h SDCCgen.h SDCCicode.h \
 SDCCbitv.h SDCCset.h SDCCast.h SDCCdebug.h SDCCutil.h SDCCasm.h \
 SDCCsystem.h port.h SDCCargs.h ../support/util/newalloc.h \
 ../support/util/dbuf_string.h ../support/util/dbuf.h
SDCCicode.o: SDCCicode.c common.h SDCCglobl.h SDCCset.h ../sdccconf.h \
 SDCCerr.h SDCCmem.h ../support/util/dbuf.h SDCCsymt.h SDCChasht.h \
 SDCCval.h SDCCast.h SDCCy.h SDCCbitv.h SDCCicode.h SDCClabel.h \
 SDCCBBlock.h SDCCloop.h SDCCcse.h SDCCcflow.h SDCCdflow.h SDCClrange.h \
 SDCCptropt.h SDCCopt.h SDCCglue.h SDCCpeeph.h SDCCgen.h SDCCicode.h \
 SDCCbitv.h SDCCset.h SDCCast.h SDCCdebug.h SDCCutil.h SDCCasm.h \
 SDCCsystem.h port.h SDCCargs.h ../support/util/newalloc.h \
 ../support/util/dbuf_string.h ../support/util/dbuf.h
SDCCbitv.o: SDCCbitv.c common.h SDCCglobl.h SDCCset.h ../sdccconf.h \
 SDCCerr.h SDCCmem.h ../support/util/dbuf.h SDCCsymt.h SDCChasht.h \
 SDCCval.h SDCCast.h SDCCy.h SDCCbitv.h SDCCicode.h SDCClabel.h \
 SDCCBBlock.h SDCCloop.h SDCCcse.h SDCCcflow.h SDCCdflow.h SDCClrange.h \
 SDCCptropt.h SDCCopt.h SDCCglue.h SDCCpeeph.h SDCCgen.h SDCCicode.h \
 SDCCbitv.h SDCCset.h SDCCast.h SDCCdebug.h SDCCutil.h SDCCasm.h \
 SDCCsystem.h port.h SDCCargs.h ../support/util/newalloc.h
SDCCset.o: SDCCset.c ../support/util/newalloc.h SDCCerr.h SDCCset.h
SDCClabel.o: SDCClabel.c common.h SDCCglobl.h SDCCset.h ../sdccconf.h \
 SDCCerr.h SDCCmem.h ../support/util/dbuf.h SDCCsymt.h SDCChasht.h \
 SDCCval.h SDCCast.h SDCCy.h SDCCbitv.h SDCCicode.h SDCClabel.h \
 SDCCBBlock.h SDCCloop.h SDCCcse.h SDCCcflow.h SDCCdflow.h SDCClrange.h \
 SDCCptropt.h SDCCopt.h SDCCglue.h SDCCpeeph.h SDCCgen.h SDCCicode.h \
 SDCCbitv.h SDCCset.h SDCCast.h SDCCdebug.h SDCCutil.h SDCCasm.h \
 SDCCsystem.h port.h SDCCargs.h ../support/util/newalloc.h
SDCCBBlock.o: SDCCBBlock.c common.h SDCCglobl.h SDCCset.h ../sdccconf.h \
 SDCCerr.h SDCCmem.h ../support/util/dbuf.h SDCCsymt.h SDCChasht.h \
 SDCCval.h SDCCast.h SDCCy.h SDCCbitv.h SDCCicode.h SDCClabel.h \
 SDCCBBlock.h SDCCloop.h SDCCcse.h SDCCcflow.h SDCCdflow.h SDCClrange.h \
 SDCCptropt.h SDCCopt.h SDCCglue.h SDCCpeeph.h SDCCgen.h SDCCicode.h \
 SDCCbitv.h SDCCset.h SDCCast.h SDCCdebug.h SDCCutil.h SDCCasm.h \
 SDCCsystem.h port.h SDCCargs.h ../support/util/newalloc.h \
 ../support/util/dbuf_string.h ../support/util/dbuf.h
SDCCloop.o: SDCCloop.c common.h SDCCglobl.h SDCCset.h ../sdccconf.h \
 SDCCerr.h SDCCmem.h ../support/util/dbuf.h SDCCsymt.h SDCChasht.h \
 SDCCval.h SDCCast.h SDCCy.h SDCCbitv.h SDCCicode.h SDCClabel.h \
 SDCCBBlock.h SDCCloop.h SDCCcse.h SDCCcflow.h SDCCdflow.h SDCClrange.h \
 SDCCptropt.h SDCCopt.h SDCCglue.h SDCCpeeph.h SDCCgen.h SDCCicode.h \
 SDCCbitv.h SDCCset.h SDCCast.h SDCCdebug.h SDCCutil.h SDCCasm.h \
 SDCCsystem.h port.h SDCCargs.h ../support/util/newalloc.h
SDCCcse.o: SDCCcse.c common.h SDCCglobl.h SDCCset.h ../sdccconf.h \
 SDCCerr.h SDCCmem.h ../support/util/dbuf.h SDCCsymt.h SDCChasht.h \
 SDCCval.h SDCCast.h SDCCy.h SDCCbitv.h SDCCicode.h SDCClabel.h \
 SDCCBBlock.h SDCCloop.h SDCCcse.h SDCCcflow.h SDCCdflow.h SDCClrange.h \
 SDCCptropt.h SDCCopt.h SDCCglue.h SDCCpeeph.h SDCCgen.h SDCCicode.h \
 SDCCbitv.h SDCCset.h SDCCast.h SDCCdebug.h SDCCutil.h SDCCasm.h \
 SDCCsystem.h port.h SDCCargs.h ../support/util/newalloc.h \
 ../support/util/dbuf_string.h ../support/util/dbuf.h
SDCCcflow.o: SDCCcflow.c common.h SDCCglobl.h SDCCset.h ../sdccconf.h \
 SDCCerr.h SDCCmem.h ../support/util/dbuf.h SDCCsymt.h SDCChasht.h \
 SDCCval.h SDCCast.h SDCCy.h SDCCbitv.h SDCCicode.h SDCClabel.h \
 SDCCBBlock.h SDCCloop.h SDCCcse.h SDCCcflow.h SDCCdflow.h SDCClrange.h \
 SDCCptropt.h SDCCopt.h SDCCglue.h SDCCpeeph.h SDCCgen.h SDCCicode.h \
 SDCCbitv.h SDCCset.h SDCCast.h SDCCdebug.h SDCCutil.h SDCCasm.h \
 SDCCsystem.h port.h SDCCargs.h ../support/util/newalloc.h
SDCCdflow.o: SDCCdflow.c common.h SDCCglobl.h SDCCset.h ../sdccconf.h \
 SDCCerr.h SDCCmem.h ../support/util/dbuf.h SDCCsymt.h SDCChasht.h \
 SDCCval.h SDCCast.h SDCCy.h SDCCbitv.h SDCCicode.h SDCClabel.h \
 SDCCBBlock.h SDCCloop.h SDCCcse.h SDCCcflow.h SDCCdflow.h SDCClrange.h \
 SDCCptropt.h SDCCopt.h SDCCglue.h SDCCpeeph.h SDCCgen.h SDCCicode.h \
 SDCCbitv.h SDCCset.h SDCCast.h SDCCdebug.h SDCCutil.h SDCCasm.h \
 SDCCsystem.h port.h SDCCargs.h ../support/util/newalloc.h
SDCClrange.o: SDCClrange.c common.h SDCCglobl.h SDCCset.h ../sdccconf.h \
 SDCCerr.h SDCCmem.h ../support/util/dbuf.h SDCCsymt.h SDCChasht.h \
 SDCCval.h SDCCast.h SDCCy.h SDCCbitv.h SDCCicode.h SDCClabel.h \
 SDCCBBlock.h SDCCloop.h SDCCcse.h SDCCcflow.h SDCCdflow.h SDCClrange.h \
 SDCCptropt.h SDCCopt.h SDCCglue.h SDCCpeeph.h SDCCgen.h SDCCicode.h \
 SDCCbitv.h SDCCset.h SDCCast.h SDCCdebug.h SDCCutil.h SDCCasm.h \
 SDCCsystem.h port.h SDCCargs.h ../support/util/newalloc.h
SDCCptropt.o: SDCCptropt.c common.h SDCCglobl.h SDCCset.h ../sdccconf.h \
 SDCCerr.h SDCCmem.h ../support/util/dbuf.h SDCCsymt.h SDCChasht.h \
 SDCCval.h SDCCast.h SDCCy.h SDCCbitv.h SDCCicode.h SDCClabel.h \
 SDCCBBlock.h SDCCloop.h SDCCcse.h SDCCcflow.h SDCCdflow.h SDCClrange.h \
 SDCCptropt.h SDCCopt.h SDCCglue.h SDCCpeeph.h SDCCgen.h SDCCicode.h \
 SDCCbitv.h SDCCset.h SDCCast.h SDCCdebug.h SDCCutil.h SDCCasm.h \
 SDCCsystem.h port.h SDCCargs.h ../support/util/newalloc.h
SDCCpeeph.o: SDCCpeeph.c common.h SDCCglobl.h SDCCset.h ../sdccconf.h \
 SDCCerr.h SDCCmem.h ../support/util/dbuf.h SDCCsymt.h SDCChasht.h \
 SDCCval.h SDCCast.h SDCCy.h SDCCbitv.h SDCCicode.h SDCClabel.h \
 SDCCBBlock.h SDCCloop.h SDCCcse.h SDCCcflow.h SDCCdflow.h SDCClrange.h \
 SDCCptropt.h SDCCopt.h SDCCglue.h SDCCpeeph.h SDCCgen.h SDCCicode.h \
 SDCCbitv.h SDCCset.h SDCCast.h SDCCdebug.h SDCCutil.h SDCCasm.h \
 SDCCsystem.h port.h SDCCargs.h ../support/util/newalloc.h \
 ../support/util/dbuf_string.h ../support/util/dbuf.h
SDCCglue.o: SDCCglue.c common.h SDCCglobl.h SDCCset.h ../sdccconf.h \
 SDCCerr.h SDCCmem.h ../support/util/dbuf.h SDCCsymt.h SDCChasht.h \
 SDCCval.h SDCCast.h SDCCy.h SDCCbitv.h SDCCicode.h SDCClabel.h \
 SDCCBBlock.h SDCCloop.h SDCCcse.h SDCCcflow.h SDCCdflow.h SDCClrange.h \
 SDCCptropt.h SDCCopt.h SDCCglue.h SDCCpeeph.h SDCCgen.h SDCCicode.h \
 SDCCbitv.h SDCCset.h SDCCast.h SDCCdebug.h SDCCutil.h SDCCasm.h \
 SDCCsystem.h port.h SDCCargs.h ../support/util/newalloc.h \
 ../support/util/dbuf_string.h ../support/util/dbuf.h
SDCCasm.o: SDCCasm.c common.h SDCCglobl.h SDCCset.h ../sdccconf.h \
 SDCCerr.h SDCCmem.h ../support/util/dbuf.h SDCCsymt.h SDCChasht.h \
 SDCCval.h SDCCast.h SDCCy.h SDCCbitv.h SDCCicode.h SDCClabel.h \
 SDCCBBlock.h SDCCloop.h SDCCcse.h SDCCcflow.h SDCCdflow.h SDCClrange.h \
 SDCCptropt.h SDCCopt.h SDCCglue.h SDCCpeeph.h SDCCgen.h SDCCicode.h \
 SDCCbitv.h SDCCset.h SDCCast.h SDCCdebug.h SDCCutil.h SDCCasm.h \
 SDCCsystem.h port.h SDCCargs.h ../support/util/newalloc.h \
 ../support/util/dbuf_string.h ../support/util/dbuf.h
SDCCmacro.o: SDCCmacro.c common.h SDCCglobl.h SDCCset.h ../sdccconf.h \
 SDCCerr.h SDCCmem.h ../support/util/dbuf.h SDCCsymt.h SDCChasht.h \
 SDCCval.h SDCCast.h SDCCy.h SDCCbitv.h SDCCicode.h SDCClabel.h \
 SDCCBBlock.h SDCCloop.h SDCCcse.h SDCCcflow.h SDCCdflow.h SDCClrange.h \
 SDCCptropt.h SDCCopt.h SDCCglue.h SDCCpeeph.h SDCCgen.h SDCCicode.h \
 SDCCbitv.h SDCCset.h SDCCast.h SDCCdebug.h SDCCutil.h SDCCasm.h \
 SDCCsystem.h port.h SDCCargs.h ../support/util/newalloc.h \
 ../support/util/dbuf_string.h ../support/util/dbuf.h
SDCCutil.o: SDCCutil.c ../support/util/dbuf.h SDCCglobl.h SDCCset.h \
 ../sdccconf.h SDCCerr.h SDCCmacro.h SDCChasht.h SDCCutil.h \
 ../support/util/newalloc.h ../support/util/dbuf_string.h \
 ../support/util/dbuf.h ../support/util/findme.h version.h
SDCCdebug.o: SDCCdebug.c common.h SDCCglobl.h SDCCset.h ../sdccconf.h \
 SDCCerr.h SDCCmem.h ../support/util/dbuf.h SDCCsymt.h SDCChasht.h \
 SDCCval.h SDCCast.h SDCCy.h SDCCbitv.h SDCCicode.h SDCClabel.h \
 SDCCBBlock.h SDCCloop.h SDCCcse.h SDCCcflow.h SDCCdflow.h SDCClrange.h \
 SDCCptropt.h SDCCopt.h SDCCglue.h SDCCpeeph.h SDCCgen.h SDCCicode.h \
 SDCCbitv.h SDCCset.h SDCCast.h SDCCdebug.h SDCCutil.h SDCCasm.h \
 SDCCsystem.h port.h SDCCargs.h ../support/util/newalloc.h
cdbFile.o: cdbFile.c common.h SDCCglobl.h SDCCset.h ../sdccconf.h \
 SDCCerr.h SDCCmem.h ../support/util/dbuf.h SDCCsymt.h SDCChasht.h \
 SDCCval.h SDCCast.h SDCCy.h SDCCbitv.h SDCCicode.h SDCClabel.h \
 SDCCBBlock.h SDCCloop.h SDCCcse.h SDCCcflow.h SDCCdflow.h SDCClrange.h \
 SDCCptropt.h SDCCopt.h SDCCglue.h SDCCpeeph.h SDCCgen.h SDCCicode.h \
 SDCCbitv.h SDCCset.h SDCCast.h SDCCdebug.h SDCCutil.h SDCCasm.h \
 SDCCsystem.h port.h SDCCargs.h ../support/util/newalloc.h
SDCCdwarf2.o: SDCCdwarf2.c common.h SDCCglobl.h SDCCset.h ../sdccconf.h \
 SDCCerr.h SDCCmem.h ../support/util/dbuf.h SDCCsymt.h SDCChasht.h \
 SDCCval.h SDCCast.h SDCCy.h SDCCbitv.h SDCCicode.h SDCClabel.h \
 SDCCBBlock.h SDCCloop.h SDCCcse.h SDCCcflow.h SDCCdflow.h SDCClrange.h \
 SDCCptropt.h SDCCopt.h SDCCglue.h SDCCpeeph.h SDCCgen.h SDCCicode.h \
 SDCCbitv.h SDCCset.h SDCCast.h SDCCdebug.h SDCCutil.h SDCCasm.h \
 SDCCsystem.h port.h SDCCargs.h ../support/util/newalloc.h SDCCdwarf2.h
SDCCerr.o: SDCCerr.c SDCCglobl.h SDCCset.h ../sdccconf.h SDCCerr.h
SDCCsystem.o: SDCCsystem.c SDCCglobl.h SDCCset.h ../sdccconf.h SDCCerr.h \
 SDCCutil.h SDCChasht.h ../support/util/dbuf.h \
 ../support/util/dbuf_string.h ../support/util/dbuf.h SDCCsystem.h \
 ../support/util/newalloc.h
SDCCgen.o: SDCCgen.c common.h SDCCglobl.h SDCCset.h ../sdccconf.h \
 SDCCerr.h SDCCmem.h ../support/util/dbuf.h SDCCsymt.h SDCChasht.h \
 SDCCval.h SDCCast.h SDCCy.h SDCCbitv.h SDCCicode.h SDCClabel.h \
 SDCCBBlock.h SDCCloop.h SDCCcse.h SDCCcflow.h SDCCdflow.h SDCClrange.h \
 SDCCptropt.h SDCCopt.h SDCCglue.h SDCCpeeph.h SDCCgen.h SDCCicode.h \
 SDCCbitv.h SDCCset.h SDCCast.h SDCCdebug.h SDCCutil.h SDCCasm.h \
 SDCCsystem.h port.h SDCCargs.h ../support/util/newalloc.h \
 ../support/util/dbuf_string.h ../support/util/dbuf.h
SDCCgas.o: SDCCgas.c SDCCgas.h SDCCglobl.h SDCCset.h ../sdccconf.h \
 SDCCerr.h SDCCmem.h ../support/util/dbuf.h SDCCsymt.h SDCChasht.h \
 SDCCval.h SDCCicode.h SDCCbitv.h SDCCast.h port.h SDCCargs.h SDCCpeeph.h \
 SDCCgen.h SDCCicode.h SDCCbitv.h SDCCset.h SDCCast.h \
 ../support/util/newalloc.h ../support/util/dbuf_string.h \
 ../support/util/dbuf.h
SDCClex.o: SDCClex.c common.h SDCCglobl.h SDCCset.h ../sdccconf.h \
 SDCCerr.h SDCCmem.h ../support/util/dbuf.h SDCCsymt.h SDCChasht.h \
 SDCCval.h SDCCast.h SDCCy.h SDCCbitv.h SDCCicode.h SDCClabel.h \
 SDCCBBlock.h SDCCloop.h SDCCcse.h SDCCcflow.h SDCCdflow.h SDCClrange.h \
 SDCCptropt.h SDCCopt.h SDCCglue.h SDCCpeeph.h SDCCgen.h SDCCicode.h \
 SDCCbitv.h SDCCset.h SDCCast.h SDCCdebug.h SDCCutil.h SDCCasm.h \
 SDCCsystem.h port.h SDCCargs.h ../support/util/newalloc.h \
 ../support/util/dbuf_string.h ../support/util/dbuf.h
NewAlloc.o: ../support/util/NewAlloc.c ../support/util/newalloc.h
dbuf.o: ../support/util/dbuf.c ../support/util/dbuf.h
dbuf_string.o: ../support/util/dbuf_string.c \
 ../support/util/dbuf_string.h ../support/util/dbuf.h
findme.o: ../support/util/findme.c ../support/util/system.h \
 ../support/util/findme.h
SDCCbtree.o: SDCCbtree.cc common.h SDCCglobl.h SDCCset.h ../sdccconf.h \
 SDCCerr.h SDCCmem.h ../support/util/dbuf.h SDCCsymt.h SDCChasht.h \
 SDCCval.h SDCCast.h SDCCy.h SDCCbitv.h SDCCicode.h SDCClabel.h \
 SDCCBBlock.h SDCCloop.h SDCCcse.h SDCCcflow.h SDCCdflow.h SDCClrange.h \
 SDCCptropt.h SDCCopt.h SDCCglue.h SDCCpeeph.h SDCCgen.h SDCCicode.h \
 SDCCbitv.h SDCCset.h SDCCast.h SDCCdebug.h SDCCutil.h SDCCasm.h \
 SDCCsystem.h port.h SDCCargs.h ../support/util/newalloc.h SDCCbtree.h
SDCClospre.o: SDCClospre.cc SDCClospre.hpp SDCCsymt.h SDCChasht.h \
 SDCCglobl.h SDCCset.h ../sdccconf.h SDCCerr.h ../support/util/dbuf.h \
 SDCCval.h SDCCicode.h SDCCbitv.h SDCCast.h SDCCmem.h SDCCgen.h \
 SDCCicode.h SDCCbitv.h SDCCset.h SDCCast.h SDCCBBlock.h SDCCopt.h \
 SDCCy.h SDCCasm.h port.h SDCCargs.h SDCCpeeph.h SDCCtree_dec.hpp
SDCCnaddr.o: SDCCnaddr.cc SDCCnaddr.hpp SDCCsymt.h SDCChasht.h \
 SDCCglobl.h SDCCset.h ../sdccconf.h SDCCerr.h ../support/util/dbuf.h \
 SDCCval.h SDCCicode.h SDCCbitv.h SDCCast.h SDCCmem.h SDCCBBlock.h \
 SDCCopt.h SDCCy.h SDCCtree_dec.hpp
